sudo: required
dist: trusty

language: python

python:
   - "3.5"

addons:
  apt:
    sources:
      - deadsnakes

before_install:
  - sudo apt_get update -q
  - make pkgs

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install numpy
    - pip install pylint

before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version
    - pylint   --version

script:
  - make test

notifications:
  email: false
  slack: 
    rooms:
      - cs373f-idb:QaAbYCyhgZdVXO9RRyiBYyas#travis
